"""add_missing_fields_and_roles

Revision ID: e79d7f65a76e
Revises: a21f0af6bf7c
Create Date: 2026-06-04 00:42:20.933975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79d7f65a76e'
down_revision: Union[str, Sequence[str], None] = 'a21f0af6bf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('rooms', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('rooms', sa.Column('last_message_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'last_message_at')
    op.drop_column('rooms', 'avatar_url')
    op.drop_column('room_members', 'role')
    # ### end Alembic commands ###
